title: Milo Noir
email: bmilan1985@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  This is the personal website of Milán Boleradszki.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: milonoir
github_username:  milonoir

# Build settings
markdown: kramdown

permalink: pretty

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

t:
  en:
    home:
      name: home
      url: /
    projects:
      name: projects
      url: /projects/
    about:
      name: about
      url: /about/
    copyright: Milán Boleradszki
  hu:
    home:
      name: főoldal
      url: /fooldal/
    projects:
      name: projektek
      url: /projektek/
    about:
      name: rólam
      url: /rolam/
    copyright: Boleradszki Milán
